### ISSUE TITLE
temperature factors > 100 change to their value -100

### ISSUE THREAD

**Issue by brgstfzj** [osita-sunday-nnyigide/Pras_Server#5] opened 2023-09-14 12:41 UTC
when running 7K6D through the server, the temperature factors of the residue with number 305 are changed.

in the original file, the ATOM lines of the residue 305 look like this:
```
ATOM   2316  N   PHE A 305       6.485  -9.951 -10.012  1.00100.33           N  
ATOM   2317  CA  PHE A 305       7.198 -10.845  -9.105  1.00102.61           C  
ATOM   2318  C   PHE A 305       6.500 -12.193  -8.969  1.00103.17           C  
ATOM   2319  O   PHE A 305       5.659 -12.552  -9.791  1.00103.53           O  
ATOM   2320  CB  PHE A 305       7.342 -10.190  -7.729  1.00103.60           C  
ATOM   2321  CG  PHE A 305       7.804  -8.765  -7.788  1.00104.63           C  
ATOM   2322  CD1 PHE A 305       9.142  -8.465  -7.975  1.00105.37           C  
ATOM   2323  CD2 PHE A 305       6.897  -7.725  -7.673  1.00105.18           C  
ATOM   2324  CE1 PHE A 305       9.570  -7.153  -8.039  1.00105.87           C  
ATOM   2325  CE2 PHE A 305       7.319  -6.411  -7.737  1.00105.78           C  
ATOM   2326  CZ  PHE A 305       8.658  -6.124  -7.920  1.00106.04           C
```

and after running through the server, they are like this:

```
ATOM   2348  N   PHE A 305       6.485  -9.951 -10.012  1.00  0.33           N  
ATOM   2349  CA  PHE A 305       7.198 -10.845  -9.105  1.00  2.61           C  
ATOM   2350  C   PHE A 305       6.500 -12.193  -8.969  1.00  3.17           C  
ATOM   2351  O   PHE A 305       5.659 -12.552  -9.791  1.00  3.53           O  
ATOM   2352  CB  PHE A 305       7.342 -10.190  -7.729  1.00  3.60           C  
ATOM   2353  CG  PHE A 305       7.804  -8.765  -7.788  1.00  4.63           C  
ATOM   2354  CD1 PHE A 305       9.142  -8.465  -7.975  1.00  5.37           C  
ATOM   2355  CD2 PHE A 305       6.897  -7.725  -7.673  1.00  5.18           C  
ATOM   2356  CE1 PHE A 305       9.570  -7.153  -8.039  1.00  5.87           C  
ATOM   2357  CE2 PHE A 305       7.319  -6.411  -7.737  1.00  5.78           C  
ATOM   2358  CZ  PHE A 305       8.658  -6.124  -7.920  1.00  6.04           C 
```

so the temperature factors (last column before the element) have been subtracted by 100.

**Comment by osita-sunday-nnyigide** [comment] 2023-09-14 13:17
Okay, I will fix it within 24 hrs. It may have been caused by the range of
index I assigned to temperature factors variable in ReadMaster.py

Thanks.

**Comment by osita-sunday-nnyigide** [comment] 2023-09-14 16:54
Hi, I have fixed the issue with the temperature factors.

Thanks.

**Closed as completed** 2023-09-15 07:34 UTC
